<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.Core" />
    <PackageReference Include="Hangfire.MySqlStorage" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="MySql.EntityFrameworkCore" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Polly.Core" />
    <PackageReference Include="Skender.Stock.Indicators" />
    <PackageReference Include="System.Data.SqlClient" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ThaiX.Domain\ThaiX.Domain.csproj" />
    <ProjectReference Include="..\ThaiX.Application\ThaiX.Application.csproj" />
  </ItemGroup>

</Project>
