using MediatR;
using Microsoft.EntityFrameworkCore;
using ThaiX.Application.Common.Constants;
using ThaiX.Application.Common.Exceptions;
using ThaiX.Application.Common.Interfaces;
using ThaiX.Application.Common.Interfaces.Messaging;
using ThaiX.Application.Features.Trading.Common;
using ThaiX.Domain.Aggregates.TradingSuggestions;

namespace ThaiX.Application.Features.Trading.Queries.ExportWeeklySuggestionTemplate;

public sealed record ExportWeeklySuggestionTemplateQuery : IAppQuery<WeeklySuggestionTemplateFileDto>
{
    public required string ReportKey { get; init; }
    public required SuggestionAssetClass AssetClass { get; init; }
    public required string Format { get; init; }
}

public sealed record WeeklySuggestionTemplateFileDto
{
    public required string FileName { get; init; }
    public required string ContentType { get; init; }
    public required byte[] FileContent { get; init; }
}

public sealed class ExportWeeklySuggestionTemplateQueryHandler
    : IRequestHandler<ExportWeeklySuggestionTemplateQuery, WeeklySuggestionTemplateFileDto>
{
    private readonly IApplicationDbContext _dbContext;
    private readonly IFileStorage _fileStorage;

    public ExportWeeklySuggestionTemplateQueryHandler(
        IApplicationDbContext dbContext,
        IFileStorage fileStorage)
    {
        _dbContext = dbContext;
        _fileStorage = fileStorage;
    }

    public async Task<WeeklySuggestionTemplateFileDto> Handle(
        ExportWeeklySuggestionTemplateQuery request,
        CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(request.ReportKey))
        {
            throw new OperationFailedException(ErrorCodes.INVALID_REQUEST, "Report key is required.");
        }

        var normalizedFormat = NormalizeFormat(request.Format);
        var storageKey = BuildStorageKey(normalizedFormat, request.ReportKey, request.AssetClass);
        var fileName = BuildFileName(normalizedFormat, request.ReportKey, request.AssetClass);
        var contentType = GetContentType(normalizedFormat);

        // Prefer pre-rendered template generated by background jobs.
        try
        {
            await using var preRenderedStream = await _fileStorage.GetAsync(storageKey, cancellationToken);
            var preRenderedBytes = await ReadToEndAsync(preRenderedStream, cancellationToken);
            return new WeeklySuggestionTemplateFileDto
            {
                FileName = fileName,
                ContentType = contentType,
                FileContent = preRenderedBytes
            };
        }
        catch (OperationFailedException ex) when (ex.ErrorCode == ErrorCodes.FILE_NOT_FOUND)
        {
            // Fallback to on-demand render for historical data where template file does not exist yet.
        }

        var report = await _dbContext.WeeklySuggestionReports
            .AsNoTracking()
            .Include(x => x.Items)
            .FirstOrDefaultAsync(
                x => x.ReportKey == request.ReportKey && x.AssetClass == request.AssetClass,
                cancellationToken);

        if (report is null)
        {
            throw new OperationFailedException(ErrorCodes.RESOURCE_NOT_FOUND, "Weekly suggestion report not found.");
        }

        var context = new WeeklySuggestionTemplateContext(
            ReportKey: report.ReportKey,
            RunAtUtc: report.RunAtUtc,
            AssetClass: report.AssetClass,
            Status: report.Status,
            Items: report.Items
                .OrderBy(x => x.Timeframe)
                .ThenBy(x => x.Rank)
                .Select(x => new WeeklySuggestionTemplateItem(
                    Timeframe: x.Timeframe,
                    Rank: x.Rank,
                    Symbol: x.Symbol,
                    MarketType: x.MarketType,
                    CompositeScore: x.CompositeScore,
                    Signal: x.Signal,
                    Confidence: x.Confidence,
                    EntryPrice: x.EntryPrice,
                    StopLoss: x.StopLoss,
                    TakeProfit1: x.TakeProfit1,
                    TakeProfit2: x.TakeProfit2))
                .ToList());

        var renderedBytes = normalizedFormat switch
        {
            "csv" => WeeklySuggestionReportTemplateRenderer.RenderCsv(context),
            _ => WeeklySuggestionReportTemplateRenderer.RenderMarkdown(context)
        };

        await using (var saveStream = new MemoryStream(renderedBytes, writable: false))
        {
            await _fileStorage.SaveAsync(saveStream, storageKey, contentType, cancellationToken);
        }

        return new WeeklySuggestionTemplateFileDto
        {
            FileName = fileName,
            ContentType = contentType,
            FileContent = renderedBytes
        };
    }

    private static string NormalizeFormat(string format)
    {
        if (string.IsNullOrWhiteSpace(format))
        {
            return "csv";
        }

        var normalized = format.Trim().ToLowerInvariant();
        return normalized switch
        {
            "csv" => "csv",
            "md" => "markdown",
            "markdown" => "markdown",
            _ => throw new OperationFailedException(
                ErrorCodes.INVALID_REQUEST,
                "Invalid format. Supported values: csv, md, markdown.")
        };
    }

    private static string BuildStorageKey(string normalizedFormat, string reportKey, SuggestionAssetClass assetClass)
        => normalizedFormat == "csv"
            ? WeeklySuggestionReportTemplateStorage.BuildCsvStorageKey(reportKey, assetClass)
            : WeeklySuggestionReportTemplateStorage.BuildMarkdownStorageKey(reportKey, assetClass);

    private static string BuildFileName(string normalizedFormat, string reportKey, SuggestionAssetClass assetClass)
        => normalizedFormat == "csv"
            ? WeeklySuggestionReportTemplateStorage.BuildCsvFileName(reportKey, assetClass)
            : WeeklySuggestionReportTemplateStorage.BuildMarkdownFileName(reportKey, assetClass);

    private static string GetContentType(string normalizedFormat)
        => normalizedFormat == "csv"
            ? "text/csv"
            : "text/markdown";

    private static async Task<byte[]> ReadToEndAsync(Stream stream, CancellationToken cancellationToken)
    {
        await using var memoryStream = new MemoryStream();
        await stream.CopyToAsync(memoryStream, cancellationToken);
        return memoryStream.ToArray();
    }
}
